gonmarfer2/Acme-Toolkits

.settings/org.eclipse.wst.common.component, CONTRIBUTORS.txt
Updated the file CONTRIBUTORS.txt with my personal contact data.
=> #5 Updated the CONTRIBUTORS.txt

.classpath, .project, .settings/org.eclipse.wst.common.component
Some errors appeared due to an apparent misconfiguration that was
slid into the project.
=> Project configuration fixed

logs/application.log, logs/populator.log, src/main/webapp/WEB-INF/views/fragments/welcome-en.i18n, src/main/webapp/WEB-INF/views/fragments/welcome-es.i18n
New welcome message for Acme-Toolkits in both languages
=> Task 019: done closes #36

src/main/java/acme/currencies/Currency.java, src/main/java/acme/currencies/CurrencyType.java
Creation of class Currency and enum CurrencyType.
=> Task 036: Done. Closes #65

reports/model_S2.uxf
Updated model with default entities.
=> Task 029: done.

src/main/java/acme/components/Component.java
Updated component class, changed Range with Length.
=> Task 033: done

src/main/java/acme/toolkits/Toolkit.java
Updated toolkit class, changed range with length.
=> Task 035: done

src/main/java/acme/tool/Tool.java
Added Tool entity with all the constraints necessary for its correct
behaviour. Closes #62
=> Task 034: added Tool entity

reports/model_S2.uxf
Updated UML model added entities: Patron DashBoard y Administrator
DashBoard.
=> Task 029: done

src/main/java/acme/entities/announcements/Announcement.java
Change info name in Announcement class.
=> Task 032: Done

reports/model_S2.uxf, src/main/java/acme/entities/components/Component.java, src/main/java/acme/entities/spam/Spam.java, src/main/java/acme/entities/spam/SpamType.java, src/main/java/acme/tool/Tool.java
Created Spam and SpamType classes.
=> Task 039: Done

src/main/java/acme/entities/components/Component.java, src/main/java/acme/forms/PatronDashBoard.java, src/main/java/acme/tool/Tool.java
=> Task 042: Done

src/main/java/acme/entities/patronage/Patronage.java, src/main/java/acme/entities/patronage/PatronageStatus.java
All done unless period constraint
=> Task 037: Initial version

src/main/java/acme/entities/tool/Tool.java
The name of the package has change accordingly to the rest of the
project.
=> Task-034: fixed Tool package name

src/main/java/acme/entities/patronage/Patronage.java, src/main/java/acme/entities/patronagereports/PatronageReport.java
Entity PatronageReport done unless code constraint
=> Task 038: first version

reports/model_S2.uxf, src/main/webapp/WEB-INF/resources/sample-data/inventor.csv, src/main/webapp/WEB-INF/resources/sample-data/patron.csv, src/main/webapp/WEB-INF/resources/sample-data/user-account.csv
Created assorted sorted data: inventor and patron linked with their accounts.
=> Task 044: done

src/main/java/acme/entities/item/Item.java, src/main/java/acme/entities/item/ItemType.java, src/main/java/acme/entities/quantity/Quantity.java
=> Task 048: added Item and Quantity entities

src/main/java/acme/entities/configuration/SystemConfiguration.java
It contains the system default properties like spam words, threshold and
currencies. Closes #149
=> Task-049: created SystemConfiguration entity

src/main/java/acme/entities/configuration/SystemConfiguration.java, src/main/webapp/WEB-INF/resources/initial-data/system-configuration.csv
Also fixed errata on the SystemConfiguration entity.
Closes #152
=> Task-050: added initial data for the system configuration.

src/main/webapp/WEB-INF/resources/sample-data/patronage-report.csv, src/main/webapp/WEB-INF/resources/sample-data/patronage.csv
Changed attributes names from camelCase to kebab.
=> Task 044/R1: done

reports/model_S2.uxf, src/main/java/acme/entities/patronagereports/PatronageReport.java, src/main/webapp/WEB-INF/resources/sample-data/announcement.csv, src/main/webapp/WEB-INF/resources/sample-data/chirp.csv, src/main/webapp/WEB-INF/resources/sample-data/patronage-report.csv, src/main/webapp/WEB-INF/resources/sample-data/patronage.csv, src/main/webapp/WEB-INF/resources/sample-data/toolkit.csv
Added variants for the sample data csv files.
Closes #167
=> Task-052: added more examples to sample data

src/main/webapp/WEB-INF/resources/initial-data/authenticated.csv
Deleted authenticated.csv file as it is said in the README of the new
workspace.
=> Task-044: done

logs/application.log, src/main/java/acme/features/any/toolkits/AnyToolkitController.java, src/main/java/acme/features/any/toolkits/AnyToolkitListService.java, src/main/java/acme/features/any/toolkits/AnyToolkitRepository.java, src/main/webapp/WEB-INF/views/any/toolkit/form.jsp, src/main/webapp/WEB-INF/views/any/toolkit/list.jsp, src/main/webapp/WEB-INF/views/any/toolkit/messages-en.i18n, src/main/webapp/WEB-INF/views/any/toolkit/messages-es.i18n
Created list of all published toolkit functionality.
=> Task-060: done.

src/main/java/acme/features/any/useraccount/AnyUserAccountController.java, src/main/java/acme/features/any/useraccount/AnyUserAccountRepository.java, src/main/java/acme/features/any/useraccount/AnyUserAccountShowService.java, src/main/webapp/WEB-INF/views/any/user-account/form.jsp, src/main/webapp/WEB-INF/views/any/user-account/messsages-en.i18n, src/main/webapp/WEB-INF/views/any/user-account/messsages-es.i18n
When the url is entered, a form with the name, surname, email and roles
is shown to any user.
=> Task-054: show user accounts

src/main/java/acme/features/patron/patronage/PatronPatronageListAllService.java, src/main/java/acme/features/patron/patronage/PatronPatronageListController.java, src/main/java/acme/features/patron/patronage/PatronPatronageListMineService.java, src/main/java/acme/features/patron/patronage/PatronPatronageRepository.java, src/main/webapp/WEB-INF/views/patron/patronage/list.jsp, src/main/webapp/WEB-INF/views/patron/patronage/messages-en.i18n, src/main/webapp/WEB-INF/views/patron/patronage/messages-es.i18n
Translations are also provided. Closes #197
=> Task-076: added list for Patrons' Patronages

src/main/java/acme/features/any/chirp/AnyChirpController.java, src/main/java/acme/features/any/chirp/AnyChirpListService.java, src/main/java/acme/features/any/chirp/AnyChirpRepository.java, src/main/webapp/WEB-INF/views/any/chirp/list.jsp, src/main/webapp/WEB-INF/views/any/chirp/messages-en.i18n, src/main/webapp/WEB-INF/views/any/chirp/messages-es.i18n
List the chirps that are not older than one month.
=> Task 055: Done

src/main/java/acme/features/administrator/configuration/AdministratorConfigurationController.java, src/main/java/acme/features/administrator/configuration/AdministratorConfigurationRepository.java, src/main/java/acme/features/administrator/configuration/AdministratorConfigurationShowService.java, src/main/webapp/WEB-INF/views/administrator/system-configuration/form.jsp, src/main/webapp/WEB-INF/views/administrator/system-configuration/messages-en.i18n, src/main/webapp/WEB-INF/views/administrator/system-configuration/messages-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu-en.i18n, src/main/webapp/WEB-INF/views/fragments/menu-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu.jsp
Show system configuration for administrator implemented.
=> Task 081: Done.

src/main/java/acme/features/inventor/patronageReports/InventorPatronageReportController.java, src/main/java/acme/features/inventor/patronageReports/InventorPatronageReportListService.java, src/main/java/acme/features/inventor/patronageReports/InventorPatronageReportRepository.java, src/main/webapp/WEB-INF/views/inventor/patronage-report/list.jsp, src/main/webapp/WEB-INF/views/inventor/patronage-report/messages-en.i18n, src/main/webapp/WEB-INF/views/inventor/patronage-report/messages-es.i18n
List of Patronage Report of a individual inventor has been created.
=> Task 074: Done.

src/main/java/acme/features/inventor/patronageReports/InventorPatronageReportController.java, src/main/java/acme/features/inventor/patronageReports/InventorPatronageReportRepository.java, src/main/java/acme/features/inventor/patronageReports/InventorPatronageReportShowService.java, src/main/webapp/WEB-INF/views/fragments/menu-en.i18n, src/main/webapp/WEB-INF/views/fragments/menu-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu.jsp, src/main/webapp/WEB-INF/views/inventor/patronage-report/form.jsp, src/main/webapp/WEB-INF/views/inventor/patronage-report/messages-en.i18n, src/main/webapp/WEB-INF/views/inventor/patronage-report/messages-es.i18n
Added Show Inventor Patronage Reports and links for main menu.
=> Task 075: Done

src/main/webapp/WEB-INF/views/fragments/menu-en.i18n, src/main/webapp/WEB-INF/views/fragments/menu-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu.jsp, src/test/java/acme/testing/any/chirp/AnyChirpListTest.java, src/test/resources/any/chirp/list.csv
=> Task 055/T: Done

src/main/java/acme/features/any/item/AnyItemRepository.java
Revision to change son jpql query in order to improve readability.
=> Task 057/R: Done.

src/test/java/acme/testing/patron/patronagereport/PatronPatronageReportListTest.java, src/test/resources/patron/patronageReport/list.csv
Created tests to test list and show from patronage-report on patrons.
=> Task 079/T: done.

reports/D02/model_S2.uxf, src/main/java/acme/entities/announcement/Announcement.java, src/main/java/acme/entities/patronageReport/PatronageReport.java, src/main/java/acme/features/any/userAccount/AnyUserAccountController.java, src/main/java/acme/features/any/userAccount/AnyUserAccountRepository.java, src/main/java/acme/features/any/userAccount/AnyUserAccountShowService.java
Detected during the follow up session
=> follow-up: added more fixes to the domain model detected

src/main/java/acme/features/inventor/patronages/InventorPatronageController.java, src/main/java/acme/features/inventor/patronages/InventorPatronageShowService.java, src/main/webapp/WEB-INF/views/inventor/patronage/form.jsp
=> Task 073: Done

src/main/java/acme/entities/configuration/SystemConfiguration.java, src/main/java/acme/features/patron/dashboard/PatronDashboardController.java, src/main/java/acme/features/patron/dashboard/PatronDashboardRepository.java, src/main/java/acme/features/patron/dashboard/PatronDashboardShowService.java, src/main/java/acme/forms/PatronDashboard.java, src/main/webapp/WEB-INF/views/fragments/menu-en.i18n, src/main/webapp/WEB-INF/views/fragments/menu-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu.jsp, src/main/webapp/WEB-INF/views/patron/patron-dashboard/form.jsp, src/main/webapp/WEB-INF/views/patron/patron-dashboard/messages-en.i18n, src/main/webapp/WEB-INF/views/patron/patron-dashboard/messages-es.i18n
Accessible from the Patron menu, it shows all required data for the
patronages that belong to a patron.
=> Task-080: Patron Dashboard added

src/main/java/acme/features/any/item/AnyItemController.java, src/main/java/acme/features/any/item/AnyItemListComponentToolkitService.java, src/main/java/acme/features/any/item/AnyItemListToolToolkitService.java, src/main/java/acme/features/any/item/AnyItemRepository.java, src/main/webapp/WEB-INF/views/any/toolkit/form.jsp, src/main/webapp/WEB-INF/views/any/toolkit/messages-en.i18n, src/main/webapp/WEB-INF/views/any/toolkit/messages-es.i18n
Included two buttons: one to see tool and other to see component.
=> Task 062/R2: fixed show view

src/main/java/acme/features/any/userAccount/AnyUserAccountRepository.java, src/main/java/acme/features/inventor/patronages/InventorPatronageListService.java, src/main/java/acme/features/inventor/patronages/InventorPatronageShowService.java, src/main/webapp/WEB-INF/views/inventor/patronage/form.jsp, src/main/webapp/WEB-INF/views/inventor/patronage/list.jsp, src/main/webapp/WEB-INF/views/inventor/patronage/messages-en.i18n, src/main/webapp/WEB-INF/views/inventor/patronage/messages-es.i18n, src/test/java/acme/testing/inventor/patronage/InventorPatronageListTest.java, src/test/java/acme/testing/patron/patronage/PatronPatronageListMineTest.java, src/test/resources/inventor/patronage/list.csv
Finished testing Patronages from an Inventor as well as details.
=> Task 073/T: done.

src/main/webapp/WEB-INF/views/any/chirp/list.jsp
=> Task 055: Fixed

src/main/java/acme/features/any/toolkit/AnyToolkitShowService.java, src/main/java/acme/features/inventor/item/InventorItemController.java, src/main/java/acme/features/inventor/item/InventorItemListComponentToolkitService.java, src/main/java/acme/features/inventor/item/InventorItemListToolToolkitService.java, src/main/java/acme/features/inventor/item/InventorItemRepository.java, src/main/java/acme/features/inventor/toolkit/InventorToolkitListService.java, src/main/java/acme/features/inventor/toolkit/InventorToolkitShowService.java, src/main/webapp/WEB-INF/resources/sample-data/item.csv, src/main/webapp/WEB-INF/views/any/toolkit/form.jsp, src/main/webapp/WEB-INF/views/any/toolkit/list.jsp, src/main/webapp/WEB-INF/views/any/toolkit/messages-en.i18n, src/main/webapp/WEB-INF/views/any/toolkit/messages-es.i18n, src/main/webapp/WEB-INF/views/fragments/menu.jsp, src/main/webapp/WEB-INF/views/inventor/toolkit/form.jsp, src/main/webapp/WEB-INF/views/inventor/toolkit/list.jsp, src/main/webapp/WEB-INF/views/inventor/toolkit/messages-en.i18n, src/main/webapp/WEB-INF/views/inventor/toolkit/messages-es.i18n
Changed links in order to control the authorise when accessing to some non public toolkit.
=> Task 071/R: hotfixes after after follow-up

src/main/java/acme/features/inventor/patronages/InventorPatronageShowService.java, src/main/webapp/WEB-INF/views/inventor/patronage/form.jsp, src/main/webapp/WEB-INF/views/inventor/patronage/messages-en.i18n, src/main/webapp/WEB-INF/views/inventor/patronage/messages-es.i18n
=> Task 073: Fixed

src/test/java/acme/testing/patron/patronage/PatronPatronageListMineTest.java, src/test/resources/patron/patronage/list.csv
They wouldn't run due to a lack of attributes that have changed in their
view
=> Task-076/T: fixed tests after project remodelling

src/main/webapp/WEB-INF/views/patron/patron-dashboard/form.jsp, src/test/java/acme/testing/patron/patronDashboard/PatronPatronDashboard.java, src/test/resources/patron/patron-dashboard/form.csv
Patron Dashboard Test finished
=> Task 080: Done

src/test/java/acme/testing/inventor/item/InventorItemShowTest.java
=> Task 069: Fixed

src/test/java/acme/testing/inventor/item/InventorItemShowTest.java
=> Task-076/T: fixed InventorItemShowTest

src/test/java/acme/testing/any/item/AnyItemListTest.java, src/test/java/acme/testing/inventor/patronage/InventorPatronageListTest.java, src/test/java/acme/testing/inventor/toolkit/InventorToolkitListTest.java, src/test/java/acme/testing/patron/patronageReport/PatronPatronageReportListTest.java, src/test/resources/any/item/component/list.csv, src/test/resources/any/item/tool/list.csv, src/test/resources/inventor/patronage/list.csv
Need to adjust tests after the change of the menu.jsp and dictionaries.
=> Task 071/t: corrected tests

.classpath, src/main/java/acme/entities/patronage/Patronage.java, src/main/java/acme/features/patron/patronage/PatronPatronageController.java, src/main/java/acme/features/patron/patronage/PatronPatronageCreateService.java, src/main/java/acme/features/patron/patronage/PatronPatronageDeleteService.java, src/main/java/acme/features/patron/patronage/PatronPatronageListService.java, src/main/java/acme/features/patron/patronage/PatronPatronagePublishService.java, src/main/java/acme/features/patron/patronage/PatronPatronageRepository.java, src/main/java/acme/features/patron/patronage/PatronPatronageShowService.java, src/main/java/acme/features/patron/patronage/PatronPatronageUpdateService.java, src/main/webapp/WEB-INF/resources/sample-data/patronage.csv, src/main/webapp/WEB-INF/views/patron/patronage/form.jsp, src/main/webapp/WEB-INF/views/patron/patronage/list.jsp, src/main/webapp/WEB-INF/views/patron/patronage/messages-en.i18n, src/main/webapp/WEB-INF/views/patron/patronage/messages-es.i18n
-Create their patronages.
-Update their patronages, as long as they're not published.
-Delete their patronages, as long as they're not published.
-Publish their patronages.
=> Task 097: Done

src/main/java/acme/features/patron/patronage/PatronPatronageCreateService.java, src/main/java/acme/features/patron/patronage/PatronPatronagePublishService.java, src/main/java/acme/features/patron/patronage/PatronPatronageUpdateService.java
PatronPatronage classes updated due to a misunderstood with group
delivery and spam detector
=> Task 097: Minor change.

src/main/java/acme/features/patron/patronage/PatronPatronageCreateService.java, src/main/java/acme/features/patron/patronage/PatronPatronagePublishService.java, src/main/java/acme/features/patron/patronage/PatronPatronageUpdateService.java, src/main/webapp/WEB-INF/views/patron/patronage/messages-en.i18n, src/main/webapp/WEB-INF/views/patron/patronage/messages-es.i18n
Now we verified if the currency in budget patronage is admitted.
=> Task 097: Done.

.classpath, .project, .settings/org.eclipse.wst.common.component, src/main/java/acme/features/any/chirp/AnyChirpController.java, src/main/java/acme/features/any/chirp/AnyChirpCreateService.java, src/main/java/acme/features/any/chirp/AnyChirpRepository.java, src/main/webapp/WEB-INF/views/any/chirp/form.jsp, src/main/webapp/WEB-INF/views/any/chirp/list.jsp, src/main/webapp/WEB-INF/views/any/chirp/messages-en.i18n, src/main/webapp/WEB-INF/views/any/chirp/messages-es.i18n
=> Task 091. Done

src/main/java/acme/features/administrator/configuration/AdministratorConfigurationController.java, src/main/java/acme/features/administrator/configuration/AdministratorConfigurationUpdateService.java, src/main/webapp/WEB-INF/views/administrator/system-configuration/form.jsp, src/main/webapp/WEB-INF/views/administrator/system-configuration/messages-en.i18n, src/main/webapp/WEB-INF/views/administrator/system-configuration/messages-es.i18n
Administrator Configuration Update done
=> Task 099: Done

src/main/java/acme/features/inventor/item/InventorItemCreateService.java, src/main/java/acme/features/inventor/item/InventorItemShowService.java, src/main/java/acme/features/inventor/item/InventorItemUpdateService.java, src/main/java/acme/features/patron/patronage/PatronPatronageCreateService.java, src/main/java/acme/features/patron/patronage/PatronPatronageShowService.java, src/main/java/acme/features/patron/patronage/PatronPatronageUpdateService.java, src/main/webapp/WEB-INF/views/inventor/item/form.jsp, src/main/webapp/WEB-INF/views/patron/patronage/form.jsp
Due to a bad commit, the  form.jsp file from inventors/item was missing plus there were some errors when updating an item.
=> Task 092: corrected errors from accepted currency

src/test/java/acme/testing/inventor/item/InventorItemShowTest.java, src/test/resources/inventor/item/component/list.csv, src/test/resources/inventor/item/list.csv, src/test/resources/inventor/item/tool/list.csv
=> Task 069/T: Fixed

src/test/java/acme/testing/patron/patronage/PatronPatronageListMineTest.java, src/test/resources/patron/patronage/list.csv
Fix list my patronages test. Due to updates some test were returning failure.
=> Task 079/T: fix test

src/main/webapp/WEB-INF/views/inventor/patronage-report/form.jsp, src/test/java/acme/testing/inventor/patronageReport/InventorPatronageReportTest.java
Test fixed due to S4 repercussions in our project.
=> Task 075/T: Fix test.

src/main/java/acme/features/administrator/announcement/AdministratorAnnouncementCreateService.java, src/main/java/acme/features/administrator/announcement/AdministratorAnnouncementRepository.java, src/main/java/acme/features/any/chirp/AnyChirpCreateService.java, src/main/java/acme/features/any/chirp/AnyChirpRepository.java, src/main/java/acme/features/inventor/item/InventorItemCreateService.java, src/main/java/acme/features/spam/SpamDetectorRepository.java, src/main/java/acme/features/spam/SpamDetectorService.java
Following the recommendations of the professors.
=> Task-100: moved spam detection to its own service

src/main/java/acme/features/any/item/AnyItemController.java, src/main/java/acme/features/any/item/AnyItemListComponentToolkitService.java, src/main/java/acme/features/any/item/AnyItemListToolToolkitService.java, src/main/java/acme/features/any/item/AnyItemRepository.java, src/test/java/acme/testing/inventor/toolkit/InventorToolkitListTest.java, src/test/resources/administrator/announcement/list.csv, src/test/resources/administrator/systemConfiguration/list.csv, src/test/resources/inventor/toolkit/list.csv
Corrected test after merging all the branches.
=> Task 098\T: Done
